{% set name = "wdlTools" %}
{% set version = "0.12.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dnanexus-rnd/wdlTools/archive/{{ version }}.tar.gz
  sha256: de3e7f0111875584958d19d1416ef0f98a7cd6362f736d6f3dfd0f9c6ccc39fe

build:
  skip: true  # [not unix]
  number: 0

requirements:
  build:
    - openjdk =8
    - sbt
    - make
    - wget
  run:
    - openjdk =8|11
    - python


test:
  commands:
    - wdltools --help

about:
  home: https://github.com/dnanexus-rnd/wdlTools
  license: Apache-2.0
  license_file: LICENSE
  summary: Scala programming language library for parsing WDL, and command-line tools for type-checking, code formatting, and more.
  dev_url: https://github.com/dnanexus-rnd/wdlTools

extra:
  recipe-maintainers:
    - jdidion
    - rhpvorderman
