{% set name = "wdlTools" %}
{% set version = "0.12.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dnanexus-rnd/wdlTools/archive/{{ version }}.tar.gz
  sha256: dd0c92e26e8209078c2be7771397f649da86692214625f315bd9936e995a5d9e
build:
  skip: true  # [not unix]
  number: 0

requirements:
  build:
    - openjdk =8
    - sbt
    - make
    - wget
  run:
    - openjdk =8|11
    - python


test:
  commands:
    - wdltools --help

about:
  home: https://github.com/dnanexus-rnd/wdlTools
  license: Apache-2.0
  license_file: LICENSE
  summary: Scala programming language library for parsing WDL, and command-line tools for type-checking, code formatting, and more.
  dev_url: https://github.com/dnanexus-rnd/wdlTools

extra:
  recipe-maintainers:
    - jdidion
    - rhpvorderman
