{% set name = "wdlTools" %}
{% set version = "0.12.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dnanexus-rnd/wdlTools/archive/{{ version }}.tar.gz
  sha256: 718856aba4c8be41c561c43a5d80d0b1a73c8384560cc09d61eeab7a2d0281e8

build:
  skip: true  # [not unix]
  number: 0

requirements:
  build:
    - openjdk =8
    - sbt
    - make
    - wget
  run:
    - openjdk =8|11
    - python


test:
  commands:
    - wdltools --help

about:
  home: https://github.com/dnanexus-rnd/wdlTools
  license: Apache-2.0
  license_file: LICENSE
  summary: Scala programming language library for parsing WDL, and command-line tools for type-checking, code formatting, and more.
  dev_url: https://github.com/dnanexus-rnd/wdlTools

extra:
  recipe-maintainers:
    - jdidion
    - rhpvorderman
