{% set name = "wdlTools" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dnanexus-rnd/wdlTools/archive/{{ version }}.tar.gz
  sha256: 6255c622e0c439eb18843242150f6d2be2a83e574ac4fea065cbdf2394181033

build:
  skip: true  # [not unix]
  number: 0

requirements:
  build:
    - openjdk =8
    - sbt
    - make
    - wget
  run:
    - openjdk =8|11
    - python


test:
  commands:
    - wdltools --help

about:
  home: https://github.com/dnanexus-rnd/wdlTools
  license: Apache-2.0
  license_file: LICENSE
  summary: Scala programming language library for parsing WDL, and command-line tools for type-checking, code formatting, and more.
  dev_url: https://github.com/dnanexus-rnd/wdlTools

extra:
  recipe-maintainers:
    - jdidion
    - rhpvorderman
